# standard jekyll configuration
markdown:         rdiscount
pygments:         true
paginate:         10     //the number of post per page
permalink:        /:year/:month/:day/:title.html
safe:             true
auto:             true

# configuration required for some pages
title:            DongFang's Blog
feed:             /atom.xml
author:
    name:         Liu Dongfang
    email:        qixi.liudongfang@gmail.com
description:      "DongFang's Blog"

about: 			  "I am Liu Dongfang, a programmer working with Android."

blogName: 		  DongFang's Blog
blogDesc: 		  Program, Economy & Life.

# configuration for ehancements, uncomment to enable
github:
    username: liudongfang

